
package com.univ.it.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebServiceDataBase", targetNamespace = "http://ws.it.univ.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWebServiceDataBase {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/addTableRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/addTableResponse")
    public boolean addTable(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/dropTableRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/dropTableResponse")
    public boolean dropTable(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns com.univ.it.ws.WebServiceTableArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/getTablesRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/getTablesResponse")
    public WebServiceTableArray getTables();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/addRowRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/addRowResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.it.univ.com/IWebServiceDataBase/addRow/Fault/Exception")
    })
    public void addRow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.univ.it.ws.WebServiceTable
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/calculateDifferenceBetweenRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/calculateDifferenceBetweenResponse")
    public WebServiceTable calculateDifferenceBetween(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/saveRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/saveResponse", fault = {
        @FaultAction(className = FileNotFoundException_Exception.class, value = "http://ws.it.univ.com/IWebServiceDataBase/save/Fault/FileNotFoundException")
    })
    public void save()
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.univ.it.ws.WebServiceTable
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.it.univ.com/IWebServiceDataBase/getTableRequest", output = "http://ws.it.univ.com/IWebServiceDataBase/getTableResponse")
    public WebServiceTable getTable(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
