
package com.univ.it.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceDataBaseService", targetNamespace = "http://ws.it.univ.com/", wsdlLocation = "http://localhost:10001/service?wsdl")
public class WebServiceDataBaseService
    extends Service
{

    private final static URL WEBSERVICEDATABASESERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEDATABASESERVICE_EXCEPTION;
    private final static QName WEBSERVICEDATABASESERVICE_QNAME = new QName("http://ws.it.univ.com/", "WebServiceDataBaseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10001/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEDATABASESERVICE_WSDL_LOCATION = url;
        WEBSERVICEDATABASESERVICE_EXCEPTION = e;
    }

    public WebServiceDataBaseService() {
        super(__getWsdlLocation(), WEBSERVICEDATABASESERVICE_QNAME);
    }

    public WebServiceDataBaseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEDATABASESERVICE_QNAME, features);
    }

    public WebServiceDataBaseService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEDATABASESERVICE_QNAME);
    }

    public WebServiceDataBaseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEDATABASESERVICE_QNAME, features);
    }

    public WebServiceDataBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDataBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWebServiceDataBase
     */
    @WebEndpoint(name = "WebServiceDataBasePort")
    public IWebServiceDataBase getWebServiceDataBasePort() {
        return super.getPort(new QName("http://ws.it.univ.com/", "WebServiceDataBasePort"), IWebServiceDataBase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebServiceDataBase
     */
    @WebEndpoint(name = "WebServiceDataBasePort")
    public IWebServiceDataBase getWebServiceDataBasePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.it.univ.com/", "WebServiceDataBasePort"), IWebServiceDataBase.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEDATABASESERVICE_EXCEPTION!= null) {
            throw WEBSERVICEDATABASESERVICE_EXCEPTION;
        }
        return WEBSERVICEDATABASESERVICE_WSDL_LOCATION;
    }

}
